services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://database:27017/recipe
    depends_on:
      - database
  database:
    image: mongo:7.0.3