GET http://{{host}}:{{port}}/api/recipes/

###

GET http://{{host}}:8089/users

###

GET http://{{host}}:8089/users/ABCDE

###

GET http://{{host}}:{{port}}/api/recipes/{{key}}

###

POST http://{{host}}:{{port}}/api/recipes/
Content-Type:application/json

{
  "authorKey":  "yxcyxc",
  "description": "A test recipe",
  "categories": [
    {
      "name": "Test",
      "parentId": null
    }
  ],
  "likes": 5,
  "key": "RECZL2GGnlWXVT",
  "difficulty": "BEGINNER",
  "creationTS": "2023-11-14T09:26:00Z",
  "ingredients": [
    {
      "name": "Pasta",
      "id": "<randomKey>",
      "quantity": 100,
      "unit": "GRAMS"
    }
  ],
  "nutrientSummary": {
    "calories": 10,
    "protein": 5,
    "carbohydrates": 5,
    "fat": 5
  },
  "titlePictureID": "picture123"
}

###

PUT http://{{host}}:{{port}}/api/recipes/
Content-Type:application/json

{
  "authorKey":  "yxcyxc",
  "description": "A test recipe",
  "categories": [
    {
      "name": "Test",
      "parentId": null
    }
  ],
  "likes": 5,
  "key": "<randomKey>",
  "difficulty": "BEGINNER",
  "creationTS": "2023-11-14T09:26:00Z",
  "comments": [
    {
      "user": {
        "id": "<randomKey>",
        "name": "Billy Bob"
      },
      "text": "Very Cool Test",
      "replyTo": null,
      "timestamp": "2023-11-15T12:32:00-08:00[America/Vancouver]"
    }
  ],
  "ingredients": [
    {
      "name": "Pasta",
      "id": "<randomKey>",
      "quantity": 100,
      "unit": "GRAMS"
    }
  ],
  "nutrientSummary": {
    "calories": 10,
    "protein": 5,
    "carbohydrates": 5,
    "fat": 5
  },
  "titlePictureID": "picture123677676"
}
> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200 No Content");
    });
%}

###
DELETE http://{{host}}:{{port}}/api/recipes/ABC123

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200 No Content");
    });
%}