GET http://{{host}}:{{port}}/api/recipes/

###

GET http://{{host}}:8089/api/users

###

GET http://{{host}}:8089/api/users/ABCDE

###

POST http://{{host}}:{{port}}/api/recipes/
Content-Type:application/json

{
  "authorKey": "yxcyxc",
  "description": "The perfect lasagna recipe made with parmesan ricotta cheese filling, melted mozzarella cheese, lasagna noodles, and a robust tomato meat sauce. It is the best lasagna recipe!",
  "categories": [
    {
      "name": "Test",
      "parentId": null
    }
  ],
  "title": "The Best Classic Lasagna Recipe",
  "likes": 5,
  "key": "<randomKey>",
  "difficulty": "BEGINNER",
  "creationTS": "2023-11-14T09:26:00Z",
  "comments": [
    {
      "user": {
        "id": "<randomKey>",
        "name": "Billy Bob"
      },
      "text": "Very Cool Test",
      "replyTo": null,
      "timestamp": "2023-11-15T12:32:00-08:00[America/Vancouver]"
    }
  ],
  "ingredients": [
    {
      "name": "Pasta",
      "id": "<randomKey>",
      "quantity": 100,
      "unit": "GRAMS"
    }
  ],
  "nutrientSummary": {
    "calories": 10,
    "protein": 5,
    "carbohydrates": 5,
    "fat": 5
  },
  "titlePictureID": "picture123"
}
